data:
  path: "F:/Zhaoyang/merged_all_pressures_separated_normalized.pt"
  batch_size: 8
  num_workers: 0  # 设置数据加载的进程数
training:
  epochs: 100
  learning_rate: 0.0001
  early_stop_patience: 500

  # ✅ 新增：损失函数选择和区域加权控制
  loss_function: svd_top3    # 损失函数类型，和上述代码一致
  lambda_main: 1.0           # 主模态loss加权系数（可调）
#  loss_function: custom_masked        # 可选 "mse" 或 "custom_masked"
  mask_enabled: false                  # 是否启用掩码区域控制
  mask_regions:                       # 多个感兴趣区域的坐标范围 [x_start, x_end, y_start, y_end]
    - [50, 75, 0, 200]
    - [125, 150, 0, 200]
  lambda_l2: 0.9                     # L2 损失权重
  lambda_mask: 0.1                    # 掩码区域损失权重

  svd_main_mode_enabled: false    # 开启主模态loss
  lambda_base: 1.0               # 基础loss权重
#  lambda_main: 0.1               # SVD主模态loss权重
  main_mode: mse                 # SVD主模态loss类型(mse, l1, energy)

model:
  output_h: 200
  output_w: 200
  input_dim: 400
  output_dim: 40000
  d_model: 512
  num_heads: 8
  num_layers: 6
  max_time_steps: 100
  attention_type: "relative"  # 这里的默认类型可以随时更改
  seq_len: 49                 # 明确指定7x7空间尺寸，支持CNN注意力

attention_types:
#  - "relative"
  - "sparse"
#  - "lsh"
#  - "se"
#  - "sk"
#  - "cbam"
#  - "bam"
#  - "eca"
#  - "danet"
#  - "psa"
#  - "shuffle"
#  - "muse"
#  - "sge"
#  - "a2"
#  - "aft"
#  - "outlook"
#  - "vip"
#  - "coatnet"
#  - "halo"
#  - "polarized"
#  - "cot"
#  - "residual"
#  - "s2"
#  - "crossformer"
#  - "moa"
#  - "dat"
#  - "parnet"
#  - "mobilevit"
#  - "mobilevitv2"

device: "cuda"

visualization:
  enabled: false        # 打开可视化
  interval: 1          # 每个epoch都保存
  max_samples: 5    # 保存每个epoch下所有batch的可视化
  save_format: "npy"   # 选择保存格式 ("npy" 或 "csv")


  do_svd_visualization: false
  svd_vis_num: 5

