analysis:
  actual_range: 0.88M - 2.26M
  individual_params:
    custom_transformer: 1.180544
    fno: 0.884272
    mlp: 2.26176
    transformer: 1.180544
    unet: 1.153601
  max_ratio: 2.5577650315739957
  target_params_M: 1.0
models:
  custom_transformer:
    attention_type: relative
    d_model: 64
    dropout: 0.1
    input_dim: 1024
    max_time_steps: 100
    model_type: custom_transformer
    num_heads: 4
    num_layers: 1
    output_dim: 16384
    output_head_type: global
    pe_type: learnable_1d
    seq_len: 11
    time_encoding: embedding
    use_memory_concat: false
    use_memory_film: true
  fno:
    activation: gelu
    input_dim: 1024
    input_resolution:
    - 32
    - 32
    model_type: fno
    num_layers: 7
    output_dim: 16384
    output_resolution:
    - 128
    - 128
    width: 48
  mlp:
    activation: gelu
    dropout: 0.1
    hidden_dims:
    - 128
    - 128
    input_dim: 1024
    model_type: mlp
    output_dim: 16384
    use_batch_norm: true
    use_residual: true
  transformer:
    d_model: 64
    dropout: 0.1
    input_dim: 1024
    max_time_steps: 100
    model_type: transformer
    num_heads: 4
    num_layers: 1
    output_dim: 16384
    output_head_type: global
    pe_type: sinusoidal_1d
    seq_len: 11
    time_encoding: embedding
    use_memory_film: false
  unet:
    activation: relu
    features:
    - 80
    - 160
    - 320
    - 160
    - 80
    in_channels: 1
    input_dim: 1024
    input_resolution:
    - 32
    - 32
    model_type: unet
    out_channels: 1
    output_dim: 16384
    output_resolution:
    - 128
    - 128
    use_attention: false
